
name: Build and Release

on:
  push:
    tags:
      - "v*"   # 只有推送 v 开头的 tag 时才触发，比如 v1.0.0

permissions:
  contents: write  # 允许创建/修改 Release

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        shell: bash
        run: pyinstaller --onefile panargs.py

      - name: Rename build artifacts
        shell: bash
        run: |
          mkdir upload
          if [ "$RUNNER_OS" = "Windows" ]; then cp dist/panargs.exe upload/panargs-windows.exe;
          elif [ "$RUNNER_OS" = "macOS" ]; then cp dist/panargs upload/panargs-macos;
          else cp dist/panargs upload/panargs-linux; fi

      - name: Upload artifacts
        shell: bash
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: upload/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        shell: bash
        uses: actions/download-artifact@v4
        with:
          path: ./dist

      - name: Generate changelog from commits
        shell: bash
        id: changelog
        run: |
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          git log --pretty=format:'- %s' $(git describe --tags --abbrev=0 @^)..@ >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Upload to Release (create if not exists)
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Changes
            ${{ steps.changelog.outputs.changelog }}
          files: dist/**/*

